import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Menu } from "@/components/menu";
import { Roboto } from "next/font/google"


const roboto = Roboto({
  weight: ["100", "400", "900"],
  style:"italic",
  variable: "--roboto",
  subsets: ["latin"]
})


export const metadata: Metadata = {
  title: "Api dragon ball",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased flex bg-neutral-800 flex-col justify-center items-center`}
      >
        <Menu firstRoute="Primeira rota" secondROute="Segunda Rota" thirdRoute="Terceira rota"/>
        <main className="flex min-w-full min-h-full items-center justify-center ">
        {children}
        </main>
      </body>
    </html>
  );
}
